name: Docker Push Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Ver código en el mismo repositorio
        uses: actions/checkout@v3

      - name: Configurar Docker
        uses: docker/setup-buildx-action@v2

      - name: Login en Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Construir las imágenes con el tag
        working-directory: usersService
        run: |
          docker build -t matiasfontecilla/ayudantia-a-user-service:latest .
          docker tag matiasfontecilla/ayudantia-a-user-service:latest matiasfontecilla/ayudantia-a-user-service:${{ github.sha }}

      # 5. ayudantia-a-user-service Subir la imagen a Docker Hub
      - name: Push Docker image
        run: |
          docker push matiasfontecilla/ayudantia-a-user-service:latest
          docker push matiasfontecilla/ayudantia-a-user-service:${{ github.sha }}